### ISSUE TITLE
how to add new template from rails

### ISSUE THREAD

**Issue by denics** [camertron/mosaico-example#1]
In the exhaustive documentation for the mosaico-rails engine, you describe how to add a new template and it works fine. But here mosaico-rails is an engine and I am unable to add new templates following your examples.

**Comment by camertron** [comment]
Hey @denics, can you provide specific error messages or other issues that would help me debug the problem? Simply saying "it doesn't work" isn't super helpful. The best would be if you could provide a sample rails app that reproduces the problem.

**Comment by denics** [comment]
Hi @camertron , thanks. You are right, I hate when people simply say "it does not work". This is why I have forked your example: https://github.com/denics/mosaico-example 
You'll see that I have been able to override views, added a project list but not yet the templates :(

**Comment by camertron** [comment]
I just cloned your fork and looked around, but I haven't been able to find the place you're adding the template, or the template files themselves. Would you be able to push up those as well?

**Comment by denics** [comment]
yep, I've removed that because it was not working. I am trying now again. As soon as I have done I'll push

**Comment by denics** [comment]
It works!!! then maybe I should contribute to the Readme if you want. As the instructions are in the engine, it looked like I had to modify it instead then adding the mosaico.rb in the rails app.

**Comment by camertron** [comment]
Ahh I see. Yes, a README contribution would be great! You are correct, the changes should all be made in the host application, but routes and controllers in the engine can stay in the engine.
